// <auto-generated />
namespace TPModule6_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TPModule61basedb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TPModule61basedb));
        
        string IMigrationMetadata.Id
        {
            get { return "202003231441495_TPModule6-1-base-db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
