// <auto-generated />
namespace Demo10.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mig3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig3));
        
        string IMigrationMetadata.Id
        {
            get { return "202009211314554_mig3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
