// <auto-generated />
namespace TPModule6_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ArtMartialManyToMany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ArtMartialManyToMany));
        
        string IMigrationMetadata.Id
        {
            get { return "202003241453082_ArtMartialManyToMany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
